# Generated by Django 2.2.5 on 2019-09-26 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('domainExamination', models.BooleanField()),
                ('domainProduct', models.BooleanField()),
                ('domainPerformance', models.BooleanField()),
                ('directMeasure', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=1000)),
                ('finalTerm', models.BooleanField()),
                ('where', models.CharField(max_length=500)),
                ('allStudents', models.BooleanField()),
                ('sampleDescription', models.CharField(max_length=500)),
                ('frequency', models.CharField(max_length=100)),
                ('threshold', models.PositiveIntegerField()),
                ('target', models.PositiveIntegerField()),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Assessment')),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AS', 'Arts and Sciences'), ('CBA', 'Business Administration'), ('CFAM', 'Communication, Fine Arts and Media'), ('COE', 'Education'), ('CIST', 'Information Science & Technology'), ('CPACS', 'Public Affairs and Community Service'), ('GEN', 'General Education')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DataAdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=75)),
                ('cycle', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradedRubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GradGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(choices=[(1, 'Something'), (2, 'Something else')], max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
                ('author', models.CharField(blank=True, max_length=100)),
                ('beginData', models.DateField()),
                ('endData', models.DateField()),
                ('section1Comment', models.CharField(blank=True, max_length=2000)),
                ('section2Comment', models.CharField(blank=True, max_length=2000)),
                ('section3Comment', models.CharField(blank=True, max_length=2000)),
                ('section4Comment', models.CharField(blank=True, max_length=2000)),
                ('submitted', models.BooleanField()),
                ('degreeProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.DegreeProgram')),
                ('rubric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makeReports.GradedRubric')),
            ],
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fullFile', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blooms', models.CharField(choices=[('KN', 'Knowledge'), ('CO', 'Comprehension'), ('AP', 'Application'), ('AN', 'Analysis'), ('EV', 'Evaluation')], max_length=50)),
                ('gradGoals', models.ManyToManyField(to='makeReports.GradGoal')),
            ],
        ),
        migrations.CreateModel(
            name='Subassessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('assessmentVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion')),
            ],
        ),
        migrations.CreateModel(
            name='SubassessmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficient', models.PositiveIntegerField()),
                ('subassessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Subassessment')),
            ],
        ),
        migrations.CreateModel(
            name='SLOText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('goalText', models.CharField(max_length=600)),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLO')),
            ],
        ),
        migrations.CreateModel(
            name='SLOsToStakeholder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('report', models.ManyToManyField(to='makeReports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='SLOStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('SLO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLO')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='SLOInReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report')),
                ('slo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOText')),
            ],
        ),
        migrations.CreateModel(
            name='RubricItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('section', models.PositiveIntegerField()),
                ('rubricVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Rubric')),
            ],
        ),
        migrations.CreateModel(
            name='ResultCommunicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='GradedRubricItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('DNM', 'Does Not Meet/Did Not Include'), ('MC', 'Meets with Concerns'), ('ME', 'Meets')], max_length=300)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.RubricItem')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.GradedRubric')),
            ],
        ),
        migrations.AddField(
            model_name='gradedrubric',
            name='rubricVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Rubric'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.College')),
            ],
        ),
        migrations.AddField(
            model_name='degreeprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Department'),
        ),
        migrations.CreateModel(
            name='DecisionsActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisionProcess', models.CharField(max_length=3000)),
                ('decisionMakers', models.CharField(max_length=3000)),
                ('decisionTimeline', models.CharField(max_length=3000)),
                ('dataUsed', models.CharField(max_length=3000)),
                ('actionTimeline', models.CharField(max_length=3000)),
                ('SLO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLO')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report')),
            ],
        ),
        migrations.CreateModel(
            name='DataAddInfoSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement', models.FileField(upload_to='')),
                ('addInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.DataAdditionalInformation')),
            ],
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report'),
        ),
        migrations.CreateModel(
            name='AssessmentSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement', models.FileField(upload_to='')),
                ('assessmentVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataBegin', models.DateField()),
                ('dataEnd', models.DateField()),
                ('numberStudents', models.PositiveIntegerField()),
                ('overallProficient', models.PositiveIntegerField(blank=True)),
                ('assessmentVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion')),
            ],
        ),
    ]
