# Generated by Django 2.2.5 on 2019-09-29 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('makeReports', '0002_auto_20190928_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='degreeprogram',
            name='startingYear',
            field=models.PositiveIntegerField(blank=True, default=2019),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='beginData',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='endData',
            field=models.DateField(blank=True),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aac', models.BooleanField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='makeReports.Department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
