# Generated by Django 2.2.5 on 2019-09-29 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0003_auto_20190928_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
