# Generated by Django 2.2.5 on 2019-09-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0004_auto_20190929_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='year',
        ),
    ]
