# Generated by Django 2.2.5 on 2019-09-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0005_remove_report_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='year',
            field=models.PositiveIntegerField(default=2019),
            preserve_default=False,
        ),
    ]
