# Generated by Django 2.2.5 on 2019-09-29 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0006_report_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='beginData',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='endData',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='rubric',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='makeReports.GradedRubric'),
        ),
        migrations.AlterField(
            model_name='report',
            name='section1Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='section2Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='section3Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='section4Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
