# Generated by Django 2.2.5 on 2019-09-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0009_auto_20190929_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradedrubric',
            name='generalComment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gradedrubric',
            name='section1Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gradedrubric',
            name='section2Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gradedrubric',
            name='section3Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gradedrubric',
            name='section4Comment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='rubricitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubricitem',
            name='section',
            field=models.PositiveIntegerField(choices=[(1, 'I. Student Learning Outcomes'), (2, 'II. Assessment Methods'), (3, 'III. Data Collection and Analysis'), (4, 'IV. Decisions and Actions')]),
        ),
    ]
