# Generated by Django 2.2.5 on 2019-10-01 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0012_auto_20190930_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradedrubricitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='makeReports.RubricItem'),
        ),
        migrations.AlterField(
            model_name='rubricitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
