# Generated by Django 2.2.5 on 2019-10-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0014_auto_20191001_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric 2019-10-02 11:10:05.909093', max_length=150),
        ),
    ]
