# Generated by Django 2.2.5 on 2019-10-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0015_rubric_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degreeprogram',
            name='cycle',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='startingYear',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric 2019-10-02 11:16:53.494653', max_length=150),
        ),
    ]
