# Generated by Django 2.2.5 on 2019-10-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0017_auto_20191003_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentdata',
            name='dataRange',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric 2019-10-04 16:57:01.488214', max_length=150),
        ),
    ]
