# Generated by Django 2.2.5 on 2019-10-04 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0019_auto_20191004_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric 2019-10-04 17:44:16.451106', max_length=150),
        ),
    ]
