# Generated by Django 2.2.5 on 2019-10-04 03:12

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0022_auto_20191003_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_range_of_reported_data',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='ReportSupplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplement', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/supplements')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Report')),
            ],
        ),
    ]
