# Generated by Django 2.2.5 on 2019-10-06 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0023_auto_20191003_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsupplement',
            name='assessmentVersion',
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='supplements',
            field=models.ManyToManyField(to='makeReports.AssessmentSupplement'),
        ),
    ]
