# Generated by Django 2.2.5 on 2019-10-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0020_auto_20191004_1744'),
        ('makeReports', '0023_auto_20191003_2212'),
    ]

    operations = [
    ]
