# Generated by Django 2.2.5 on 2019-10-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0026_auto_20191006_1857'),
        ('makeReports', '0024_auto_20191006_2350'),
    ]

    operations = [
    ]
