# Generated by Django 2.2.5 on 2019-10-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0027_merge_20191007_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentversion',
            name='threshold',
            field=models.CharField(max_length=500),
        ),
    ]
