# Generated by Django 2.2.5 on 2019-10-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0030_auto_20191009_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dataadditionalinformation',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=3000),
        ),
    ]
