# Generated by Django 2.2.5 on 2019-10-13 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0036_announcement_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
