# Generated by Django 2.2.5 on 2019-10-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0040_auto_20191013_1200'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gradgoal',
            managers=[
            ],
        ),
    ]
