# Generated by Django 2.2.5 on 2019-10-18 23:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0043_auto_20191017_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentversion',
            name='frequencyChoice',
            field=models.CharField(choices=[('S', 'Once/semester'), ('Y', 'Once/year'), ('O', 'Other')], default='O', max_length=100),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='fullFile',
            field=models.FileField(blank=True, default='settings.STATIC_ROOT/norubric.pdf', null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='rubrics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))], verbose_name='rubric file'),
        ),
        migrations.CreateModel(
            name='AssessmentAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_proficiency', models.PositiveIntegerField(verbose_name='aggregate proficiency percentage')),
                ('met', models.BooleanField()),
                ('assessmentVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion')),
            ],
        ),
    ]
