# Generated by Django 2.2.5 on 2019-10-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0044_auto_20191018_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentversion',
            name='sampleDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='where',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='gradgoal',
            name='text',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='goalText',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='slostatus',
            name='status',
            field=models.CharField(choices=[('Met', 'Met'), ('Partially Met', 'Partially Met'), ('Not Met', 'Not Met'), ('Unknown', 'Unknown')], max_length=50),
        ),
    ]
