# Generated by Django 2.2.5 on 2019-11-11 21:37

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0049_auto_20191107_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('graph', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/graphs', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))])),
            ],
        ),
    ]
