# Generated by Django 2.2.5 on 2019-11-21 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0052_auto_20191115_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentaggregate',
            name='override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='slostatus',
            name='override',
            field=models.BooleanField(default=False),
        ),
    ]
