# Generated by Django 2.2.5 on 2019-11-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0053_auto_20191121_1632'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subassessment',
        ),
    ]
