# Generated by Django 2.2.5 on 2019-12-03 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0056_auto_20191123_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentaggregate',
            name='assessmentVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion', verbose_name='assessment version'),
        ),
    ]
