# Generated by Django 2.2.5 on 2019-09-30 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0008_auto_20190929_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aac',
            field=models.BooleanField(null=True),
        ),
    ]
