# Generated by Django 2.2.5 on 2019-10-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0011_gradedrubric_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubricitem',
            name='DMEtext',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rubricitem',
            name='EEtext',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='rubricitem',
            name='MEtext',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
