# Generated by Django 2.2.5 on 2019-10-01 21:54

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0013_auto_20190930_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='changedFromPrior',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='firstInstance',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentversion',
            name='slo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOInReport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assessmentsupplement',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='asssements/supplements'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='sampleDescription',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='where',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='dataaddinfosupplement',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/supplements'),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='fullFile',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='rubrics'),
        ),
    ]
