# Generated by Django 2.2.5 on 2019-10-04 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0017_auto_20191003_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subassessment',
            name='proficient',
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric 2019-10-03 20:39:20.292856', max_length=150),
        ),
        migrations.CreateModel(
            name='SubassessmentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficient', models.PositiveIntegerField()),
                ('subassessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Subassessment')),
            ],
        ),
    ]
