# Generated by Django 2.2.5 on 2019-10-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0018_auto_20191003_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric 2019-10-03 20:42:59.476043', max_length=150),
        ),
    ]
