# Generated by Django 2.2.5 on 2019-10-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0019_auto_20191003_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rubric',
            name='name',
            field=models.CharField(default='Rubric', max_length=150),
        ),
    ]
