# Generated by Django 2.2.5 on 2019-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0031_auto_20191009_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='numberOfAssess',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
