# Generated by Django 2.2.5 on 2019-10-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0032_report_numberofassess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='numberOfAssess',
        ),
        migrations.AddField(
            model_name='sloinreport',
            name='numberOfAssess',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
