# Generated by Django 2.2.5 on 2019-10-13 05:51

import django.core.validators
from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0034_auto_20191010_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsupplement',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='asssements/supplements', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AlterField(
            model_name='dataadditionalinformation',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/supplements', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AlterField(
            model_name='reportsupplement',
            name='supplement',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/supplements', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
        migrations.AlterField(
            model_name='rubric',
            name='fullFile',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='rubrics', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',))]),
        ),
    ]
