# Generated by Django 2.2.5 on 2019-10-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0037_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradgoal',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
