# Generated by Django 2.2.5 on 2019-10-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0039_auto_20191013_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expiration',
            field=models.DateField(),
        ),
    ]
