# Generated by Django 2.2.5 on 2019-10-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0042_auto_20191016_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentversion',
            name='frequencyChoice',
            field=models.CharField(choices=[('S', 'Once\\semester'), ('Y', 'Once\\year'), ('O', 'Other')], default='O', max_length=100),
        ),
        migrations.AlterField(
            model_name='slo',
            name='blooms',
            field=models.CharField(choices=[('KN', 'Knowledge'), ('CO', 'Comprehension'), ('AP', 'Application'), ('AN', 'Analysis'), ('SN', 'Synthesis'), ('EV', 'Evaluation')], max_length=50),
        ),
    ]
