# Generated by Django 2.2.5 on 2019-10-29 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0045_auto_20191024_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='directMeasure',
            field=models.BooleanField(verbose_name='direct measure'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='domainExamination',
            field=models.BooleanField(verbose_name='examination domain'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='domainPerformance',
            field=models.BooleanField(verbose_name='performance domain'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='domainProduct',
            field=models.BooleanField(verbose_name='product domain'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='numberOfUses',
            field=models.PositiveIntegerField(default=1, verbose_name='number of uses'),
        ),
        migrations.AlterField(
            model_name='assessmentaggregate',
            name='assessmentVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion', verbose_name='assessment version'),
        ),
        migrations.AlterField(
            model_name='assessmentaggregate',
            name='met',
            field=models.BooleanField(verbose_name='target met'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='assessmentVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion', verbose_name='assessment version'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='dataRange',
            field=models.CharField(max_length=500, verbose_name='data range'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='numberStudents',
            field=models.PositiveIntegerField(verbose_name='number of students'),
        ),
        migrations.AlterField(
            model_name='assessmentdata',
            name='overallProficient',
            field=models.PositiveIntegerField(blank=True, verbose_name='overall percentage proficient'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='allStudents',
            field=models.BooleanField(verbose_name='all students assessed'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='changedFromPrior',
            field=models.BooleanField(verbose_name='changed from prior version'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='finalTerm',
            field=models.BooleanField(verbose_name='final term'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='frequencyChoice',
            field=models.CharField(choices=[('S', 'Once/semester'), ('Y', 'Once/year'), ('O', 'Other')], default='O', max_length=100, verbose_name='frequency choice'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='sampleDescription',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='description of sample'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='slo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOInReport', verbose_name='SLO in report'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='where',
            field=models.CharField(max_length=500, verbose_name='location of assessment'),
        ),
        migrations.AlterField(
            model_name='degreeprogram',
            name='startingYear',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='starting year of cycle'),
        ),
        migrations.AlterField(
            model_name='gradedrubric',
            name='generalComment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='general comment'),
        ),
        migrations.AlterField(
            model_name='gradedrubric',
            name='rubricVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Rubric', verbose_name='rubric version'),
        ),
        migrations.AlterField(
            model_name='gradedrubric',
            name='section1Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section I comment'),
        ),
        migrations.AlterField(
            model_name='gradedrubric',
            name='section2Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section II comment'),
        ),
        migrations.AlterField(
            model_name='gradedrubric',
            name='section3Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section III comment'),
        ),
        migrations.AlterField(
            model_name='gradedrubric',
            name='section4Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section IV comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='degreeProgram',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.DegreeProgram', verbose_name='degree program'),
        ),
        migrations.AlterField(
            model_name='report',
            name='numberOfSLOs',
            field=models.PositiveIntegerField(default=0, verbose_name='number of SLOs'),
        ),
        migrations.AlterField(
            model_name='report',
            name='section1Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section I comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='section2Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section II comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='section3Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section III comment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='section4Comment',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='section IV comment'),
        ),
        migrations.AlterField(
            model_name='rubricitem',
            name='DMEtext',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='did not meet expectations text'),
        ),
        migrations.AlterField(
            model_name='rubricitem',
            name='EEtext',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='exceeded expecations text'),
        ),
        migrations.AlterField(
            model_name='rubricitem',
            name='MEtext',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='met expectations text'),
        ),
        migrations.AlterField(
            model_name='rubricitem',
            name='rubricVersion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.Rubric', verbose_name='rubric version'),
        ),
        migrations.AlterField(
            model_name='slo',
            name='blooms',
            field=models.CharField(choices=[('KN', 'Knowledge'), ('CO', 'Comprehension'), ('AP', 'Application'), ('AN', 'Analysis'), ('SN', 'Synthesis'), ('EV', 'Evaluation')], max_length=50, verbose_name="Bloom's taxonomy level"),
        ),
        migrations.AlterField(
            model_name='slo',
            name='gradGoals',
            field=models.ManyToManyField(to='makeReports.GradGoal', verbose_name='graduate-level goals'),
        ),
        migrations.AlterField(
            model_name='slo',
            name='numberOfUses',
            field=models.PositiveIntegerField(default=1, verbose_name='number of uses of this SLO'),
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='changedFromPrior',
            field=models.BooleanField(verbose_name='changed from prior version'),
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='goalText',
            field=models.CharField(max_length=1000, verbose_name='goal text'),
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='numberOfAssess',
            field=models.PositiveIntegerField(default=0, verbose_name='number of assessments'),
        ),
        migrations.AlterField(
            model_name='sloinreport',
            name='slo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLO', verbose_name='SLO'),
        ),
    ]
