# Generated by Django 2.2.5 on 2019-11-06 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0046_auto_20191029_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentaggregate',
            name='assessmentVersion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion', verbose_name='assessment version'),
        ),
        migrations.AlterField(
            model_name='assessmentversion',
            name='frequencyChoice',
            field=models.CharField(choices=[('O', 'Other'), ('S', 'Once/semester'), ('Y', 'Once/year')], default='O', max_length=100, verbose_name='frequency choice'),
        ),
    ]