# Generated by Django 2.2.5 on 2019-11-08 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0048_auto_20191107_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionsactions',
            name='sloIR',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOInReport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slostatus',
            name='sloIR',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, to='makeReports.SLOInReport'),
            preserve_default=False,
        ),
    ]