# Generated by Django 2.2.5 on 2019-11-12 01:22

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0050_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='dateTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='graph',
            name='graph',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='data/graphs'),
        ),
    ]
