# Generated by Django 2.2.5 on 2019-11-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0051_auto_20191111_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsactions',
            name='actionTimeline',
        ),
        migrations.RemoveField(
            model_name='decisionsactions',
            name='dataUsed',
        ),
        migrations.RemoveField(
            model_name='decisionsactions',
            name='decisionMakers',
        ),
        migrations.RemoveField(
            model_name='decisionsactions',
            name='decisionProcess',
        ),
        migrations.RemoveField(
            model_name='decisionsactions',
            name='decisionTimeline',
        ),
    ]
