# Generated by Django 2.2.5 on 2019-11-23 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0054_delete_subassessment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slostatus',
            name='SLO',
        ),
        migrations.RemoveField(
            model_name='slostatus',
            name='report',
        ),
    ]
