# Generated by Django 2.2.5 on 2019-11-23 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0055_auto_20191123_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decisionsactions',
            name='SLO',
        ),
        migrations.RemoveField(
            model_name='decisionsactions',
            name='report',
        ),
    ]
