# Generated by Django 2.2.5 on 2019-12-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('makeReports', '0057_auto_20191202_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentaggregate',
            name='assessmentVersion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='makeReports.AssessmentVersion', verbose_name='assessment version'),
        ),
    ]
